name: Deploy to Hostinger
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 178.16.128.41
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          server-dir: /public_html/
          exclude: |
            **/.git*
            **/.git*/**
            **/vendor/**
            **/node_modules/**
            **/.env
            **/.env.*
            **/storage/logs/**
            **/storage/framework/cache/**
            **/storage/framework/sessions/**
            **/storage/framework/views/**
            **/.phpunit.result.cache
            **/tests/**
            **/.editorconfig
            **/.gitignore
            **/.gitattributes
            **/phpunit.xml
            **/README.md